export default {
  DUPLICATED_EMAIL_ADDRESS: 'DUPLICATED_EMAIL_ADDRESS',
  DUPLICATED_NICKNAME: 'DUPLICATED_NICKNAME',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRE',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  LOGIN_FAIL: 'LOGIN_FAIL',
};
