# 환경별로 설정 분리하기

# local, dev, production 공통
server:
  port: 8080

# 실행할 환경 지정 spring:profiles:active 옵션
spring:
  profiles:
    active: prod
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# aws s3 config
cloud:
  aws:
    credentials:
       access-key: AKIA2OECFFQMIDJLD2VO
       secret-key: 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
    s3:
       bucket-name: my-journey-life
       access-url: https://my-journey-life.s3.ap-northeast-2.amazonaws.com/images
    region:
      static: ap-northeast-2
    stack:
     auto: false

# --- 로 설정을 구분하고 spring:config:active:on-profile 옵셥에 사용될 환경(local, dev, prod)를 명시
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql-rds.cuwguiwtvuh1.ap-northeast-2.rds.amazonaws.com:3306/my_journey_life
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tkppp
    password: tiffndla0423
  jpa:
    hibernate:
      ddl-auto: update