# 환경별로 설정 분리하기

# local, dev, production 공통
server:
  port: 8080

# 실행할 환경 지정 spring:profiles:active 옵션
spring:
  profiles:
    active: dev

# --- 로 설정을 구분하고 spring:config:active:on-profile 옵셥에 사용될 환경(local, dev, prod)를 명시
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: prod